/**
 * Builds `assets/fonts/embedded.css`: the open substitute faces the preview may
 * need, inlined as data URIs.
 *
 * The preview injects this into someone else's page, where an external font
 * request can be blocked by their CSP, by a network policy, or simply be slow
 * enough that the "after" capture happens before the swap — any of which makes
 * the comparison understate the correction. Embedding removes that dependency.
 *
 * Run manually when the substitute set changes; the output is committed.
 */
import fs from "node:fs";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36";

/** Both are SIL Open Font License, so embedding them is permitted. */
const FAMILIES = [
  { family: "Source Serif 4", axis: "ital,wght@0,400;0,600;1,400" },
  { family: "Archivo", axis: "wght@400;500;600;700" },
];

/** Latin coverage only: other subsets triple the size for no visible gain. */
const KEEP_SUBSET = /U\+0000-00FF|U\+0100-02AF/;

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { "user-agent": UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return res.text();
}

async function main() {
  const out: string[] = [
    "/* Generated by scripts/embed-fonts.ts — do not edit.",
    " * Source Serif 4 and Archivo, SIL Open Font License 1.1.",
    " * Embedded so preview renders never depend on an external font request.",
    " */",
  ];

  for (const { family, axis } of FAMILIES) {
    const css = await fetchText(
      `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:${axis}&display=swap`,
    );
    const blocks = css.split("@font-face").slice(1);
    let kept = 0;
    for (const block of blocks) {
      if (!KEEP_SUBSET.test(block)) continue;
      const url = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
      if (!url) continue;
      const res = await fetch(url, { headers: { "user-agent": UA } });
      if (!res.ok) continue;
      const base64 = Buffer.from(await res.arrayBuffer()).toString("base64");
      out.push(
        `@font-face${block
          .replace(/url\(https:\/\/fonts\.gstatic\.com\/[^)]+\)/, `url(data:font/woff2;base64,${base64})`)
          .trim()}`,
      );
      kept++;
    }
    console.log(`${family}: embedded ${kept} face(s)`);
  }

  const target = path.join(process.cwd(), "assets", "fonts", "embedded.css");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `${out.join("\n")}\n`);
  console.log(`wrote ${target} (${Math.round(fs.statSync(target).size / 1024)} KB)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
